FEATURE_FLAGS = {
    'CLIENT_CACHE': True,
    'ENABLE_EXPLORE_JSON_CSRF_PROTECTION': True,
    'PRESTO_EXPAND_DATA': True,
}

SECRET_KEY = 'ZsG+vS++211AJOHXFjIP1avBvinElByZPSY8z8j3uRGpi/1tqL5xrOlD'

